# <p align="center">
#   <img src="https://raw.githubusercontent.com/pr1t4m-d3y/pr1t4m-d3y/output/snake.svg" />
# </p>

#ADD THIS LINE IN README. AND RENAME TO snake.yml

# name: Generate snake animation

# on:
#   schedule: # execute every 12 hours
#     - cron: "* */12 * * *"

#   workflow_dispatch:

# jobs:
#   generate:
#     permissions:
#       contents: write
#     runs-on: ubuntu-latest
#     timeout-minutes: 5

#     steps:
#       - name: generate snake.svg
#         uses: Platane/snk/svg-only@v3
#         with:
#           github_user_name: ${{ github.repository_owner }}
#           outputs: dist/snake.svg?palette=github-dark


#       - name: push snake.svg to the output branch
#         uses: crazy-max/ghaction-github-pages@v3.1.0
#         with:
#           target_branch: output
#           build_dir: dist
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


name: Generate pacman animation

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"

  workflow_dispatch:


jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}
          theme: github-dark
           max_contributions: 9999


      - name: push pacman-contribution-graph.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
